// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHfv2KKcGyyTJJhEURBUKkQGHht1oG6GI',
    appId: '1:64600634737:web:9a481bda46cd1c914d72d0',
    messagingSenderId: '64600634737',
    projectId: 'couplay-9e2cb',
    authDomain: 'couplay-9e2cb.firebaseapp.com',
    storageBucket: 'couplay-9e2cb.appspot.com',
    measurementId: 'G-JNFXNC43SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkAUJyOvz8UGvpERDYEeUz2MtS5KT-FIs',
    appId: '1:64600634737:android:3ac7c5a2dd7707434d72d0',
    messagingSenderId: '64600634737',
    projectId: 'couplay-9e2cb',
    storageBucket: 'couplay-9e2cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcfgc7s_bqqMkbmI0vwqj6B_Pn1lYx8FI',
    appId: '1:64600634737:ios:024cd466f6c34af84d72d0',
    messagingSenderId: '64600634737',
    projectId: 'couplay-9e2cb',
    storageBucket: 'couplay-9e2cb.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcfgc7s_bqqMkbmI0vwqj6B_Pn1lYx8FI',
    appId: '1:64600634737:ios:024cd466f6c34af84d72d0',
    messagingSenderId: '64600634737',
    projectId: 'couplay-9e2cb',
    storageBucket: 'couplay-9e2cb.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHfv2KKcGyyTJJhEURBUKkQGHht1oG6GI',
    appId: '1:64600634737:web:c7dac7f44e930d424d72d0',
    messagingSenderId: '64600634737',
    projectId: 'couplay-9e2cb',
    authDomain: 'couplay-9e2cb.firebaseapp.com',
    storageBucket: 'couplay-9e2cb.appspot.com',
    measurementId: 'G-PEZ9C882EL',
  );
}
